import type { Metadata } from "next";
import "./globals.css";
import { WagmiProvider } from "wagmi";

export const metadata: Metadata = {
  title: "AIA2.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}></body>
    </html>
  );
}
